Release 2.20
Ralim/IronOS pull request #1416
Opened 2022-09-25 01:35 UTC by Ralim

Preparing for 2.20 release

2022-09-27 15:09 UTC, discip commented
@Ralim
I think we should update all the translation files prior to releasing this, because the actual description text for the CJC calibration confirmation might be a bit misleading.

The current `SettingsCalibrationWarning` is:
*`"Please make sure tip & handle are at room temperature`**`before calibration`**`!"`*

... but should be:
*`"Please make sure tip & handle are at room temperature`**`at next boot`**`!"`*

I have tried doing this in my fork but unfortunately this increases the size to no longer fit the **`TS80P`**. 😭

Do you have any idea?

2022-10-20 07:46 UTC, Ralim commented
@discip 

I'm happy for translations to be updated. I just pushed some changes to buy a few bytes in TS80P; see if your changes work now :)

2022-10-20 10:14 UTC, discip commented
@Ralim
Will definitely do as soon as I am home. 😅

2022-10-20 15:43 UTC, discip commented
@Ralim
Unfortunately there is still not enough free space. 😭

2022-10-22 00:50 UTC, Ralim commented
@discip Made a tiny bit more space, does that fit yet?

2022-10-22 01:27 UTC, Ralim commented
@discip Okay no rush but you should have room now :)

2022-10-22 08:55 UTC, discip commented
@Ralim
Now it fits. 😃 :thumbsup:

I am on it right now.
Need a bit time to include all translators & for the documentation.

2022-10-22 08:57 UTC, Ralim commented
No rush, let me know how it goes.

2022-11-26 06:52 UTC, Ralim commented
Alrighty this is overdue; anyone against this going out ?

2022-11-26 14:13 UTC, discip commented
I would like to change this:
https://github.com/Ralim/IronOS/blob/628b8fe32d81ca055683506c016f7504eaa1c6af/Translations/translation_EN.json#L300
back to:
```json
"desc": "Calibrates tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)"
```
since it did not bring the anticipated success and is somewhat *unclear*.

But I'm afraid to annoy the translators with the frequency of changes.

2022-11-26 14:14 UTC, discip commented
Before the merge,
I would like to change this:
https://github.com/Ralim/IronOS/blob/628b8fe32d81ca055683506c016f7504eaa1c6af/Translations/translation_EN.json#L300
back to:
```json
"desc": "Calibrates tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)"
```
since it did not bring the anticipated success and is somewhat *unclear*.

But I'm afraid to annoy the translators with the frequency of changes.

2022-11-26 14:15 UTC, discip commented
Before the merge,
I would like to change this:
https://github.com/Ralim/IronOS/blob/628b8fe32d81ca055683506c016f7504eaa1c6af/Translations/translation_EN.json#L300
back to:
```json
"desc": "Calibrates tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)"
```
since it did not bring the anticipated success and is somewhat *unclear*.

But I'm afraid to annoy the translators with the frequency of changes.
(Currently only federicodilo & dmitrygribenchuk are affected.)

2022-11-26 15:57 UTC, discip commented
Before the merge,
I would like to change this:
https://github.com/Ralim/IronOS/blob/628b8fe32d81ca055683506c016f7504eaa1c6af/Translations/translation_EN.json#L300
back to:
```json
"desc": "Calibrates tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)"
```
since it did not bring the anticipated success and is somewhat *unclear*.

But I'm afraid to annoy the translators with the frequency of changes.
(Currently only federicodilo & dmitrygribenchuk are affected.)

In general, I would like to revise and unify the translation one more time. 😅
Or should I wait with that?

2022-11-27 02:04 UTC, Ralim commented
Go for it by me

2022-11-27 17:24 UTC, KoopsF requested changes
translation suggestion

2022-11-27 17:24 UTC, KoopsF commented on Translations/translation_NL.json
> +		"SettingsCalibrationWarning": "Before rebooting, make sure tip & handle are at room temperature!",
Suggestion: "Zorg ervoor dat voor de volgende keer opstarten de punt én het handvat op kamertemperatuur zijn!"

2022-11-28 06:46 UTC, discip commented
Will do, as soon as I am home again. 😊

2022-12-02 20:53 UTC, Firebie commented
```
diff --git a/source/Core/BSP/Miniware/ThermoModel.cpp b/source/Core/BSP/Miniware/ThermoModel.cpp
index 1b04bd5f..a7bc8094 100644
--- a/source/Core/BSP/Miniware/ThermoModel.cpp
+++ b/source/Core/BSP/Miniware/ThermoModel.cpp
@@ -125,6 +125,6 @@ const int32_t uVtoDegC[] = {
     38137, 500, //
 };
 #endif
-const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(uint16_t));
+const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(int32_t));
 
 uint32_t TipThermoModel::convertuVToDegC(uint32_t tipuVDelta) { return Utils::InterpolateLookupTable(uVtoDegC, uVtoDegCItems, tipuVDelta); }
diff --git a/source/Core/BSP/Pinecil/ThermoModel.cpp b/source/Core/BSP/Pinecil/ThermoModel.cpp
index 846a0a00..4515c42f 100644
--- a/source/Core/BSP/Pinecil/ThermoModel.cpp
+++ b/source/Core/BSP/Pinecil/ThermoModel.cpp
@@ -67,6 +67,6 @@ const int32_t uVtoDegC[] = {
 };
 #endif
 
-const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(uint16_t));
+const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(int32_t));
 
 uint32_t TipThermoModel::convertuVToDegC(uint32_t tipuVDelta) { return Utils::InterpolateLookupTable(uVtoDegC, uVtoDegCItems, tipuVDelta); }
```

2022-12-03 14:52 UTC, alvinhochun commented
> ```
> diff --git a/source/Core/BSP/Miniware/ThermoModel.cpp b/source/Core/BSP/Miniware/ThermoModel.cpp
> index 1b04bd5f..a7bc8094 100644
> --- a/source/Core/BSP/Miniware/ThermoModel.cpp
> +++ b/source/Core/BSP/Miniware/ThermoModel.cpp
> @@ -125,6 +125,6 @@ const int32_t uVtoDegC[] = {
>      38137, 500, //
>  };
>  #endif
> -const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(uint16_t));
> +const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(int32_t));
>  
>  uint32_t TipThermoModel::convertuVToDegC(uint32_t tipuVDelta) { return Utils::InterpolateLookupTable(uVtoDegC, uVtoDegCItems, tipuVDelta); }
> diff --git a/source/Core/BSP/Pinecil/ThermoModel.cpp b/source/Core/BSP/Pinecil/ThermoModel.cpp
> index 846a0a00..4515c42f 100644
> --- a/source/Core/BSP/Pinecil/ThermoModel.cpp
> +++ b/source/Core/BSP/Pinecil/ThermoModel.cpp
> @@ -67,6 +67,6 @@ const int32_t uVtoDegC[] = {
>  };
>  #endif
>  
> -const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(uint16_t));
> +const int uVtoDegCItems = sizeof(uVtoDegC) / (2 * sizeof(int32_t));
>  
>  uint32_t TipThermoModel::convertuVToDegC(uint32_t tipuVDelta) { return Utils::InterpolateLookupTable(uVtoDegC, uVtoDegCItems, tipuVDelta); }
> ```

I would say you should use `sizeof(uVtoDegC) / (2 * sizeof(uVtoDegC[0]))`. But to be frank, I would probably declare `uVtoDegC` to be `struct { int32_t a, int32_t b }` so you can write `sizeof(uVtoDegC) / sizeof(uVtoDegC[0])`.

2022-12-11 01:01 UTC, Ralim commented
@discip Should I just release this as is?

2022-12-13 09:45 UTC, discip commented
@Ralim
Apart from the fact that I would like to see #1494 implemented, there is nothing hindering that from happening.

2022-12-13 11:38 UTC, merged