language update (follow-up on #1398)
Ralim/IronOS pull request #1432
Opened 2022-10-22 10:27 UTC by discip

After the behavior of the calibration was changed with #1398, I also had to adjust the corresponding entries in the languages.
But due to lack of space on the **`TS80P`** I had to postpone this until it was taken care of by @Ralim.

Additionally, the entries have been rearranged to match the structure present in the current menu on the corresponding device.

Also, the unused entries have been removed. (To save the trouble of translating them.)

I've tried my best to find out who contributed to each language and I hope I haven't overlooked anyone.

BE
@lidacity
@dmitrygribenchuk

BG
@dimitroffs

CS
@cewbdex

DA
@t-xdk

EL
@Devnol

ES
@Meldinov
@IkerGarcia

FI
@Dids

FR
@HanaO00

HR
@jonnieZG

HU
@balika011
@hippi-viking

IT
@federicodilo

LT
@Vinigas
@jvitkauskas

NL
@FaBjE
@KoopsF

NO
@LarsSimonsen

PL
@KITT3000
@playday3008
@d-rez

PT
@lfhohmann
@speleos

RO
@cipyyy
@sandmanRO

RU
@onxblog
@JugglerLKR
@playday3008

SK
@OndroNR
@gamelaster

SL
@pikipirs
@gigibu5

SR
@vomindoraan
@abrakatebra

SV
@piksel

TR
@JustNoLimit
@mesutkilic
@wortex1979
@muhammedfurkan42

UK
@BatsIhor
@playday3008
@eslng
@hrebeniukB

VI
@prokrypt

CJK
@alvinhochun
@i4M1k0SU
@skishida
@contactalexliu

2022-10-22 14:09 UTC, hippi-viking commented
Thank you, but please don't spam all the referenced people with all the separate commits.

2022-10-22 14:16 UTC, discip commented
@hippi-viking
Sorry!
I did not mean to spam anyone.
I was not aware of the fact, that every commit would cause a notification. 😓

2022-10-22 14:20 UTC, hippi-viking commented
No worries :) I only wrote to let you know that every commit is a separate notification for everyone referenced.

2022-10-22 14:21 UTC, Devnol commented
yeah don't worry, I've seen people do it on projects with like 14k members, absolute hell.

2022-10-22 14:36 UTC, discip commented
I am not in charge, but if you want to update your translation, just open a PR.

2022-10-22 14:36 UTC, discip commented
@Devnol
I am not in charge, but if you want to update your translation, just open a PR.

2022-10-22 18:48 UTC, discip commented
@Devnol
Sorry, I think I did not get you right the first time.

If you meant to change the lines I did update, than it is best to do it like so:
I think you know the process depicted in the attached pictures.
![1](https://user-images.githubusercontent.com/53649486/197357568-42112b17-35bb-4025-b727-8791d63bb197.png)

![2](https://user-images.githubusercontent.com/53649486/197357567-3a1813c4-603b-46ee-8cf5-e417b90e3c7b.png)

2022-10-22 18:55 UTC, discip commented
@Devnol
Sorry, I think I misunderstood you the first time.

If you wanted to change the lines I updated, the best way to do it is like this:
I think you know the process shown in the attached pictures.

![1](https://user-images.githubusercontent.com/53649486/197357837-379be896-d1df-484f-aa9a-7cf16d9fb743.png)

![2](https://user-images.githubusercontent.com/53649486/197357567-3a1813c4-603b-46ee-8cf5-e417b90e3c7b.png)

2022-10-22 19:51 UTC, prokrypt commented
VI translation is all @River-b, not me (:

2022-10-23 08:07 UTC, federicodilo requested changes
Feel free to change those or I'll do myself once merged

2022-10-23 08:07 UTC, federicodilo commented on Translations/translation_IT.json
> +			"desc": "Calibrate tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)"
Compensa l'errore delle rilevazioni della termocoppia al prossimo avvio (non necessario se l'errore su T è <5 °C)

2022-10-24 08:20 UTC, IkerGarcia commented on Translations/translation_ES.json
> +		"SettingsCalibrationWarning": "Please make sure tip & handle are at room temperature at next boot!",
```suggestion
		"SettingsCalibrationWarning": "¡Asegúrate que la punta esté a temperatura ambiente al inicio",

```

2022-10-24 08:21 UTC, IkerGarcia commented on Translations/translation_ES.json
> +			"desc": ""
```suggestion
			"desc": "Ajustes de potencia"

```

2022-10-24 08:25 UTC, IkerGarcia commented on Translations/translation_ES.json
> +			"desc": ""
```suggestion
			"desc": "Ajustes para soldar"

```

2022-10-24 08:25 UTC, IkerGarcia commented on Translations/translation_ES.json
> +			"desc": ""
```suggestion
			"desc": "Ajustes de ahorro energético"

```

2022-10-24 08:25 UTC, IkerGarcia commented on Translations/translation_ES.json
> +			"desc": ""
```suggestion
			"desc": "Ajustes de interfaz de usuario"

```

2022-10-24 08:25 UTC, IkerGarcia commented on Translations/translation_ES.json
> +			"desc": ""
```suggestion
			"desc": "Ajustes avanzados"

```

2022-10-24 08:25 UTC, IkerGarcia commented on Translations/translation_ES.json
> +				"Calibrate CJC",
```suggestion
				"Calibrar CJC",

```

2022-10-24 08:25 UTC, IkerGarcia commented on Translations/translation_ES.json
> +			"desc": "Calibrate tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)"
```suggestion
			"desc": "Calibrar compensación de punta fría en el próximo inicio (no necesario si Delta T es < 5°C)"

```

2022-10-24 11:26 UTC, cipyyy commented on Translations/translation_RO.json
> +			"desc": ""
"desc": "Setări de alimentare"

2022-10-24 11:26 UTC, cipyyy commented on Translations/translation_RO.json
> +			"desc": ""
"desc": "Setări de lipire"

2022-10-24 11:26 UTC, cipyyy commented on Translations/translation_RO.json
> +			"desc": ""
"desc": "Setări de economisire a energiei"

2022-10-24 11:26 UTC, cipyyy commented on Translations/translation_RO.json
> +			"desc": ""
"desc": "Setări interfată utilizator"

2022-10-24 11:26 UTC, cipyyy commented on Translations/translation_RO.json
> +			"desc": ""
"desc": "Optiuni avansate"

2022-10-24 21:55 UTC, discip commented
@Ralim
Good morning Ben.

This got somewhat out of hand, since people do not update the files changed in this PR but rather the present ones.

I think it would be best if you merged this in before people commit their language updates.
Otherwise this misses the point of asking people to adapt to the current situation.
 thanks

2022-10-24 22:01 UTC, discip commented
@Ralim
Good morning Ben.

This has gotten a bit out of hand as people are not updating the files changed in this PR, but the existing ones which are missing the latest information.

I think it would be best if you merged this in before people commit their language updates.

Otherwise this misses the point of asking people to adapt to the current situation.
 thanks

2022-10-24 22:15 UTC, merged

2022-10-24 22:17 UTC, discip commented
That was quick! 😮