Update translation_RU.json
Ralim/IronOS pull request #1500
Opened 2022-12-14 12:43 UTC by JugglerLKR

updated some translation. new missing desc "" translation. CJC calibration translation

- [] There are no breaking changes

2022-12-14 13:39 UTC, discip requested changes
Please revert the marked changes.

2022-12-14 13:39 UTC, discip commented on Translations/translation_RU.json
> +            "desc": "Настройки питания (от аккумуляторов, QC, PD и т.п."
```suggestion
            "desc": ""
```
Since it is not used, it was purposely removed!

2022-12-14 13:39 UTC, discip commented on Translations/translation_RU.json
> +            "desc": "Найстроки режимов и паяния, турбо-режима"
```suggestion
            "desc": ""
```
Same here.

2022-12-14 13:39 UTC, discip commented on Translations/translation_RU.json
> +            "desc": "Режимы сна для экономии питания"
```suggestion
            "desc": ""
```
And here.

2022-12-14 13:39 UTC, discip commented on Translations/translation_RU.json
> +            "desc": "Настройки интерфейса"
```suggestion
            "desc": ""
```
And here.

2022-12-14 13:39 UTC, discip commented on Translations/translation_RU.json
> +            "desc": "Дополнительные настройки"
```suggestion
            "desc": ""
```
And here.

2022-12-14 13:39 UTC, discip commented on Translations/translation_RU.json
> +            "desc": "Выбор языка"
```suggestion
            "desc": ""
```
And here.

2022-12-28 09:30 UTC, discip commented
@Ralim
I think it is best to just merge this is, since I have to adapt it in #1502 either way.

2022-12-28 10:04 UTC, merged

2022-12-28 10:12 UTC, discip commented
@Ralim
I just noticed that this PR was done towards **master** instead of **dev**. 😅

2022-12-28 10:12 UTC, Ralim commented
Ah dang it, it must have reset. On it