Improved translations for NL and NL_BE
Ralim/IronOS pull request #1830
Opened 2023-10-22 18:41 UTC by DjedenOfficial

I improved the translations for NL and NL_BE. Now it has been fully translated instead of partly. The changes haven't been tested. I would like to know how to test since I don't know how (I am new to GitHub).

2023-10-22 21:21 UTC, ia commented
> I would like to know how to test since I don't know how

Hello. Once this workflow will be approved to run tests & to prepare builds[^1], and if everything is ok, then you will see pre-built binaries as downloadable artifacts here which you can download, flash & test on hardware which you have.

[^1]: Usually it happens automatically once any pull-request is made but it seems something has been changed recently on that so now it seems like admins of the project have to trigger it manually.

2023-10-22 21:44 UTC, Ralim commented
Each new contributor needs to be approved once before the automated actions can run.

So now they should always work for you @DjedenOfficial.

Once they finish you should be able to download the compiled code from them for testing

2023-10-22 21:54 UTC, ia commented
I'm not an expert on git/github myself, but maybe another reason it's because you did make a commit not into a separate branch with different name (after you forked the repo) but into `dev` branch (which is "protected" branch because it's "_upstream_" one).

Bottom line is just a suggestion for the future, here is the recommended way to make pull-requests, @DjedenOfficial:
- fork the repo to your account (i.e., using github interface)[^1];
- clone forked repo locally: `git clone ...`[^1];
- create your own branch for your own changes (it seems this step has been skipped - that's why actions maybe haven't been triggered automatically): `git checkout -b mychange dev`, where `mychange` - name of your branch, `dev` - name of upstream branch of forked repo;
- add changes / fixes by editing files;
- make a commit: `git commit ...`;
- push your local branch with your local changes to your forked repo on github: `git push -u YOUR_GITHUB_USERNAME mychange`;
- after that once you open github it will show you that you did make a push into forked repo and github will suggest you to create pull-request automatically.

[^1]: these steps should be done only once per each repo/project

Something like that.

2023-10-22 21:59 UTC, ia commented
> I would like to know how to test

Here you go, [now here you can download](https://github.com/Ralim/IronOS/actions/runs/6605573287#artifacts) binaries with your changes to test.

2023-10-22 22:24 UTC, DjedenOfficial commented
> > I would like to know how to test
> 
> Here you go, [now here you can download](https://github.com/Ralim/IronOS/actions/runs/6605573287#artifacts) binaries with your changes to test.

Thanks testing went well I fixed some minor issues and want to run another test.

2023-10-22 22:25 UTC, Ralim commented
All good, Ill approve until this merges; so don't sweat and just give me a bit to see the email 😁

2023-10-24 09:05 UTC, Ralim commented
@DjedenOfficial Are you happy with how this looks now ?

2023-10-27 16:12 UTC, DjedenOfficial commented
> @DjedenOfficial Are you happy with how this looks now ?

Sorry for not reacting. It needs just slight changes but I will be making them as soon as possible and are likely to be done by the afternoon. Is there a way to test firmware by not making a whole pull request?

2023-10-27 21:41 UTC, Ralim commented
No rush, just that it went silent so I wasn't sure.

You can compile locally to test; or you can setup your fork to run the builds for testing.

Convention is to mark a PR as a draft until you're good to go (but don't stress, everyone misses the option)

2023-11-18 14:43 UTC, ColoMAX requested changes
From a quick glance, I've found at least these issues.

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Calibratie\ngedaan!"
Calibratie\nklaar!

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Sommige settings\nzijn veranderd!"
Instellingen\nzijn veranderd

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Geen accelerometer\ngedectecteerd!"
old was correct

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "LOCKED"
Old was correct

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "UNLOCKED"
Old was correct

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> -            "message": "!GEBLOKKEERD!"
Old was correct

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Thermisch\nop hol geslagen"
Thermische catastrofe?

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Calibreren\n"
lower case and "aan het calibreren" if it fits on screen.

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Voedingsspanning: \n"
Too long: "Ingangs V: \n"

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "message": "Jou apparaat is waarschijnlijk namaak!"
+"...een namaak!"

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "displayText": "Gebruikers-\ninterface",
Old was more Dutch sounding

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "description": "Minimale toegelate voltage"
Undo this

2023-11-18 14:43 UTC, ColoMAX commented on Translations/translation_NL.json
> +            "description": "Vermogen van de adapter"
QC is a name, you can not translate this away

2023-11-20 17:29 UTC, discip commented
@DjedenOfficial & @ColoMAX
It would be very nice if you could find a solution that you both could agree on. 😊

2023-11-20 20:21 UTC, discip commented
@DjedenOfficial & @ColoMAX
It would be very nice if you could find a solution that you both could agree on, as neither the developer nor anyone else authorized to merge this in are knowledgeable enough to judge what is best. 😊

thanks

2023-11-29 17:06 UTC, discip commented
@DjedenOfficial & @ColoMAX

Anyone?

2023-11-29 17:07 UTC, discip commented
@DjedenOfficial & @ColoMAX

Any progress yet?

2023-12-01 21:34 UTC, discip commented
@DjedenOfficial & @ColoMAX

We need a solution guys. Please answer.

2023-12-27 21:52 UTC, discip commented
@ColoMAX
> Later this week I can try to add a commit to the pr to resolve all

This was 3 weeks ago, are you still interested, if not I will merge this in as is.

2023-12-27 21:53 UTC, discip commented
@ColoMAX
> Later this week I can try to add a commit to the pr to resolve all

This was 3 weeks ago.
Are you still interested?
If not I'll merge this in as is.

2023-12-28 20:29 UTC, ColoMAX commented
@DjedenOfficial can you add me as a contributor on your fork? I can not push my changes to your repo.
Or is there another way to do it?
I've worked on the Dutch translations only, not the Flemish though, since I'm not familiar with it. Although one might consider, for the time being, to keep it the same as the Dutch until somebody comes around who does, due to the similarities between the two languages/dialects.

2024-01-08 18:52 UTC, closed without merging