improve zh_cn translation
Ralim/IronOS pull request #2019
Opened 2024-12-10 03:03 UTC by KevinTong9

- [ ] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
ZH_CN translation update

* **What is the current behavior?**
[Pinecil V1 small display error in ZH_CN](https://github.com/Ralim/IronOS/issues/1780)

* **Other information**:
It doesn't aim to fix the problem in the issue, just a translation update.

2024-12-10 06:46 UTC, discip requested changes
@KevinTong9
Have you tried the changes on your device?
If I remember correctly, you would need to remove all the new lines **`\n`** in order to make it work.

2024-12-10 06:46 UTC, discip commented on Translations/translation_ZH_CN.json
> +      "message": "欠压\n"
```suggestion
      "message": "欠压"
```

2024-12-10 06:46 UTC, discip commented on Translations/translation_ZH_CN.json
> +      "displayText": "默认\n模式"
```suggestion
      "displayText": "默认模式"
```

2024-12-10 06:46 UTC, discip commented on Translations/translation_ZH_CN.json
> +      "displayText": "安全\n模式"
```suggestion
      "displayText": "安全模式"
```

2024-12-10 06:46 UTC, discip commented on Translations/translation_ZH_CN.json
> +      "displayText": "自动\n检测"
```suggestion
      "displayText": "自动检测"
```

2024-12-10 06:46 UTC, discip commented on Translations/translation_ZH_CN.json
> +      "displayText": "霍尔传感器\n休眠时间",
```suggestion
      "displayText": "霍尔传感器休眠时间",
```

2024-12-10 06:46 UTC, discip commented on Translations/translation_ZH_CN.json
> +      "displayText": "焊接头\n类型",
```suggestion
      "displayText": "焊接头类型",
```

2024-12-10 06:53 UTC, KevinTong9 commented
> @KevinTong9 Have you tried the changes on your device? If I remember correctly, you would need to remove all the new lines **`\n`** in order to make it work.

Sorry, I haven't tested it locally as my current environment doesn't allow it. Testing might have to wait until I have some free time.

By the way, I can only test Pencil V1.

2024-12-10 07:03 UTC, KevinTong9 commented
> @KevinTong9 Have you tried the changes on your device? If I remember correctly, you would need to remove all the new lines **`\n`** in order to make it work.

**`\n`** deleted now

2024-12-10 07:15 UTC, discip approved these changes

2024-12-10 07:19 UTC, discip commented
I think it is best if you test the changes prior to merging.

I could do the testing for you as soon as I'm home again.

2024-12-10 07:19 UTC, discip commented
I think it is best if we test the changes prior to merging.

I could do the testing for you as soon as I'm home again.

2024-12-10 07:21 UTC, KevinTong9 commented
> I think it is best if we test the changes prior to merging.
> 
> I could do the testing for you as soon as I'm home again.

Tk. If I have time tonight, I can also go test V1.

2024-12-11 12:13 UTC, KevinTong9 commented
> I did test it, but in some cases I was not sure if you would be satisfied. SO from my point of view this should be good to go, but please take your time testing it yourself. 😊
> 
> kind regards

The translation works fine for me.  This looks good to go.

*That said, it did not address the problem I mentioned in the issue, which is unrelated to this PR. The issue of displaying garbled text still persists. Perhaps you could look into the root of the issue？It seems like the characters were not displayed completely. It should display "欠压" here, but with only the upper half visible now.*

![](https://github.com/user-attachments/assets/976b4458-8013-48eb-9805-8fc59692a143)

Best regards

2024-12-11 22:13 UTC, discip commented
> That said, it did not address the problem I mentioned in the issue ...

I'm pretty sure @Ralim could fix this, but I don't know if he has got time to do that. 😊

2024-12-11 23:44 UTC, ia commented
> _That said, it did not address the problem I mentioned in the issue, which is unrelated to this PR. The issue of displaying garbled text still persists. Perhaps you could look into the root of the issue？It seems like the characters were not displayed completely. It should display "欠压" here, but with only the upper half visible now._
> 
> ![](https://private-user-images.githubusercontent.com/79413138/394730700-976b4458-8013-48eb-9805-8fc59692a143.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NTk2MzIsIm5iZiI6MTczMzk1OTMzMiwicGF0aCI6Ii83OTQxMzEzOC8zOTQ3MzA3MDAtOTc2YjQ0NTgtODAxMy00OGViLTk4MDUtOGZjNTk2OTJhMTQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDIzMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYTZiNTBkMzg2NTE3YjZhNmY2NWJlMDE0OTVkNWYyMDI1NDZmYTFiZTQ5YmU5ZmFlNGU4YmQ0YWNhYThlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8T93QP8h_PENdjoyGrZ85J-Vv-FbT91OYNEVfo6qLgM)

Hello. Could you tell, please, what kind of power supply do you use so I could try to reproduce the issue? My assumption is that it's something like more or less standard 5V/1A old USB power brick but I just would like to make sure. Thanks.

P.S. Can't promise anything but will try to reproduce and think about it. _I may have_ a couple of ideas to check.

2024-12-12 02:37 UTC, ia commented
> Hello. Could you tell, please, what kind of power supply do you use so I could try to reproduce the issue? My assumption is that it's something like more or less standard 5V/1A old USB power brick but I just would like to make sure. Thanks.

And which power port do you use? DC 5525 barrel or USB-C? And what is on the other side of the cord with the iron exactly?

I tried to simulate the problem using _TS80P_ with different static sets of voltage (everything I have closer around _~5V_): with _3V3_ it doesn't turn on, with _4.5V_ it works, and even trying to heat the tip, lol.

Anyway, since @Ralim did put `\n` with [this commit](https://github.com/Ralim/IronOS/pull/2013/files), I would try to revert `\n` to the `UndervoltageString` string and to see if there is any difference.

2024-12-12 03:47 UTC, KevinTong9 commented
> > _That said, it did not address the problem I mentioned in the issue, which is unrelated to this PR. The issue of displaying garbled text still persists. Perhaps you could look into the root of the issue？It seems like the characters were not displayed completely. It should display "欠压" here, but with only the upper half visible now._
> > ![](https://private-user-images.githubusercontent.com/79413138/394730700-976b4458-8013-48eb-9805-8fc59692a143.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NTk2MzIsIm5iZiI6MTczMzk1OTMzMiwicGF0aCI6Ii83OTQxMzEzOC8zOTQ3MzA3MDAtOTc2YjQ0NTgtODAxMy00OGViLTk4MDUtOGZjNTk2OTJhMTQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDIzMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYTZiNTBkMzg2NTE3YjZhNmY2NWJlMDE0OTVkNWYyMDI1NDZmYTFiZTQ5YmU5ZmFlNGU4YmQ0YWNhYThlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8T93QP8h_PENdjoyGrZ85J-Vv-FbT91OYNEVfo6qLgM)
> 
> Hello. Could you tell, please, what kind of power supply do you use so I could try to reproduce the issue? My assumption is that it's something like more or less standard 5V/1A old USB power brick but I just would like to make sure. Thanks.
> 
> P.S. Can't promise anything but will try to reproduce and think about it. _I may have_ a couple of ideas to check.

Already: [Pinecil V1 small display error in ZH_CN](https://github.com/Ralim/IronOS/issues/1780)

- USB-C
- 5V
- Any brick will do, computer port could too.
- **Pencil V1 with B2 tip** not TS80P

2024-12-12 03:53 UTC, KevinTong9 commented
> > That said, it did not address the problem I mentioned in the issue ...
> 
> I'm pretty sure @Ralim could fix this, but I don't know if he has got time to do that. 😊

Take your time. No rush at all—whenever it’s convenient for you.

If the translation looks good, this PR should be ready to merge.

Really appreciate it!

2024-12-12 05:57 UTC, discip commented
@ia
> Anyway, since @Ralim did put `\n` with [this commit](https://github.com/Ralim/IronOS/pull/2013/files), I would try to revert `\n` to the `UndervoltageString` string and to see if there is any difference.

This won't help since the CJK languages ​​can only be drawn large.

The solution must be put in here somewhere: https://github.com/Ralim/IronOS/blob/dev/source/Core/Threads/UI/drawing/mono_96x16/draw_warning_undervoltage.cpp

I've also tested other languages ​​with the same result.

The solution would be to remove **`VIN:`** and draw the voltage on the right, but I'm not sure how to achieve the latter and unfortunately I don't have the time to get there empirically.

2024-12-12 06:02 UTC, discip commented
Merging this in and the undervoltage issue should be addressed separately, since this affects other CJK languages as well.

2024-12-12 06:03 UTC, merged

2024-12-12 19:38 UTC, ia commented
> This won't help since the CJK languages ​​can only be drawn large.

How interesting! Thank you for this piece of information and pardon me for misinformation. There are still so many nuances in the project which I'm just not fully aware yet still.

> The solution must be put in here somewhere: https://github.com/Ralim/IronOS/blob/dev/source/Core/Threads/UI/drawing/mono_96x16/draw_warning_undervoltage.cpp

Yeah, I was thinking about the same thing.

> I've also tested other languages ​​with the same result.

Aha, got it.

> The solution would be to remove **`VIN:`** and draw the voltage on the right, but I'm not sure how to achieve the latter and unfortunately I don't have the time to get there empirically.

I would like to help with this gladly, but unfortunately I have no idea how to reproduce the issue in the first place with my _TS80P_. I may have to get my hands on _Pinecil V2_ but I'm not sure if it will be reproducible there just like with _Pinecil V1_.

2024-12-12 19:47 UTC, ia commented
> If the translation looks good, this PR should be ready to merge.

@KevinTong9, but just out of curiosity, could you tell, please: what about such lines as `USBPDModeNoDynamic`, `InputVoltageString` and types of tips? Did you miss them by accident or did you decide to keep them as universal non-translatable on purpose? Just asking, thanks.